Ik 67
adrielFab/Kaasch pull request #16
Opened 2017-03-13 07:06 UTC by handriamanantena

This branch is related to receiving notifications. Sending notifications will be done in a separate branch.
Notifications can be sent through the firebase console.
If you want to test it out...

Go to the following link https://firebase.google.com/docs/notifications/android/console-device
Follow the steps in the section "Add Firebase to your app".
Here they explain how to connect firebase to the application and then send a notification the device.
sending a notification is done through their console.

2017-03-15 17:24 UTC, arosser reviewed
.

2017-03-15 17:52 UTC, arosser requested changes

2017-03-15 17:52 UTC, arosser commented on client/app/src/main/java/com/example/mrides/Notification/FirebaseInstanceIdService.java
> + * Created by Deez Nuts on 3/10/2017.
Unprofessionalism

2017-03-15 17:52 UTC, arosser commented on client/app/src/main/java/com/example/mrides/Activity/MainActivity.java
> +     * This method handles loging in and logging out the user.
typo on logging in

2017-03-15 19:53 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/MainActivity.java
> +        System.out.print(response);
If finished debugging, should remove these type of print statements.

2017-03-16 02:34 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/TempMainActivity.java
> +        //Intent intent = new Intent(TempMainActivity.this, MainActivity.class);
To remove

2017-03-16 02:47 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/MainActivity.java
>                  .enableAutoManage(this /* FragmentActivity */, (GoogleApiClient.OnConnectionFailedListener) this /* OnConnectionFailedListener */)
Remove commented code.

2017-03-16 02:48 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/MainActivity.java
>                  .enableAutoManage(this /* FragmentActivity */, (GoogleApiClient.OnConnectionFailedListener) this /* OnConnectionFailedListener */)
Remove commented code since it was replaced buy 'this'.

2017-03-16 02:48 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/MainActivity.java
> +    public void onConnectionFailed(@NonNull ConnectionResult connectionResult) {
Empty method.

2017-03-16 02:50 UTC, redfox300 commented on client/app/src/main/java/com/example/mrides/Activity/ActivityObserver.java
> +    /**
Good addition of javadoc, this should be added to at least the critical methods in your code.

2017-03-16 03:16 UTC, arosser approved these changes

2017-03-16 04:27 UTC, merged